"
Imported by VwImportClass
"
Class {
	#name : #JunOpenGLEmbeddedDisplayView,
	#superclass : #JunOpenGLDisplayView,
	#category : #'Jun-OpenGL-Display'
}

{ #category : #copyright }
JunOpenGLEmbeddedDisplayView class >> copyright [
	^'Jun799 (2015/09/19) Copyleft 1996-2015 AOKI Atsushi, ODA Tomohiro, HOSHI Takanori, NISHINAKA Yoshiyuki, YAMADA Ryousuke, WATANABE Katsuhiro, Ankur J. Chavda, NISHIHARA Satoshi, MATSUDA Ryouichi, MATSUO Minoru, Brent N. Reeves, ASAOKA Hiroko, TANAKA Shinichi, ASADA Mitsuhiro, Paul Guyot (LIP6), Albert Kerssies, MATSUBARA Nobuto, SAWAMOTO Eri, HAYASHI Koichiro, NAKAO Tatsuya, and NISHIMURA Yuuri.'
]

{ #category : #copyright }
JunOpenGLEmbeddedDisplayView class >> system [
	^'Jun'
]

{ #category : #copyright }
JunOpenGLEmbeddedDisplayView class >> version [
	^'799'
]

{ #category : #'controller accessing' }
JunOpenGLEmbeddedDisplayView >> defaultControllerClass [
	^JunOpenGLEmbeddedDisplayController
]
